;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	c-electric-delete-forward
	c-electric-paren
	c-electric-semi&comma
	c-electric-slash
	comment-region
	cua-cut-region
	cua-paste
	dired-do-kill-lines
	eval-last-sexp
	find-file
	insert-file
	kill-region
	set-fill-column
	wdired-finish-edit
	))

(setq mc/cmds-to-run-once
      '(
	mac-mwheel-scroll
	))
